
platform :ios, '9.0'

target 'MovieTrailers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieTrailers
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'BTYoutubePlayer'

end
